#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
venvDir="$dir/../venv"

if [[ ! -d "$venvDir" ]]; then
    virtualenv -p python3 "$venvDir"
fi
source "$dir/../venv/bin/activate"

requirementsPath="$dir/../requirements-dev.txt"
if [[ -f "$requirementsPath" ]]; then
    pip install -r "$requirementsPath"
else
    pip install -r "$dir/../requirements.txt"
fi
export PYTHONPATH="$PYTHONPATH:$dir/.."
